"""Camada de voz: wake word → STT → Agent Runtime → TTS.

API pública do componente. Este pacote é uma **Interface** no sentido de Ports &
Adapters ([ADR-0001](../../../docs/adr/0001-ports-and-adapters-dependency-rule.md)):
aciona o Core sem conhecê-lo. Ele não importa `jarvis.agent`, `jarvis.memory`,
`jarvis.context`, `jarvis.events` nem `jarvis.execution` — o resto do Jarvis
chega por um único port, `ConversationalAgent`, implementado no composition root
(`architecture-contracts.md §3.9`).
"""

from jarvis.voice.audio import (
    CAPTURE_FORMAT,
    MAX_CLIP_SECONDS,
    SAMPLE_WIDTH,
    AudioChunk,
    AudioFormat,
    PcmClip,
    concat,
    rms,
    silence,
)
from jarvis.voice.errors import (
    AudioDeviceError,
    AudioError,
    AudioFormatError,
    InvalidVoiceInputError,
    SpeechToTextError,
    SttAuthenticationError,
    SttInvalidResponseError,
    SttRateLimitError,
    SttRejectedError,
    SttTimeoutError,
    TextToSpeechError,
    TtsAuthenticationError,
    TtsInvalidResponseError,
    TtsRateLimitError,
    TtsRejectedError,
    TtsTimeoutError,
    VoiceError,
    VoiceRepositoryError,
    VoiceSessionError,
)
from jarvis.voice.loop import TurnOutcome, VoiceLoop, VoiceSettings
from jarvis.voice.ports import (
    AgentReply,
    AudioSink,
    AudioSource,
    ConversationalAgent,
    PlaybackResult,
    SpeechToText,
    TextToSpeech,
    Transcript,
    VoiceSessionRepository,
    WakeWordDetection,
    WakeWordDetector,
)
from jarvis.voice.session import (
    SessionSettings,
    TurnRole,
    VoiceSession,
    VoiceState,
    VoiceStatus,
    VoiceTurn,
    new_session_id,
)
from jarvis.voice.vad import SegmentEnd, Segmenter, SpeechSegment, VadSettings
from jarvis.voice.wake import WakePhrase, matches, normalize, parse_phrases

__all__ = [
    "CAPTURE_FORMAT",
    "MAX_CLIP_SECONDS",
    "SAMPLE_WIDTH",
    "AgentReply",
    "AudioChunk",
    "AudioDeviceError",
    "AudioError",
    "AudioFormat",
    "AudioFormatError",
    "AudioSink",
    "AudioSource",
    "ConversationalAgent",
    "InvalidVoiceInputError",
    "PcmClip",
    "PlaybackResult",
    "SegmentEnd",
    "Segmenter",
    "SessionSettings",
    "SpeechSegment",
    "SpeechToText",
    "SpeechToTextError",
    "SttAuthenticationError",
    "SttInvalidResponseError",
    "SttRateLimitError",
    "SttRejectedError",
    "SttTimeoutError",
    "TextToSpeech",
    "TextToSpeechError",
    "Transcript",
    "TtsAuthenticationError",
    "TtsInvalidResponseError",
    "TtsRateLimitError",
    "TtsRejectedError",
    "TtsTimeoutError",
    "TurnOutcome",
    "TurnRole",
    "VadSettings",
    "VoiceError",
    "VoiceLoop",
    "VoiceRepositoryError",
    "VoiceSession",
    "VoiceSessionError",
    "VoiceSessionRepository",
    "VoiceSettings",
    "VoiceState",
    "VoiceStatus",
    "VoiceTurn",
    "WakePhrase",
    "WakeWordDetection",
    "WakeWordDetector",
    "concat",
    "matches",
    "new_session_id",
    "normalize",
    "parse_phrases",
    "rms",
    "silence",
]
